Demo/Controllers/SachOnlineController.cs
using System;
using PagedList;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Demo.Models;
using System.Dynamic;

namespace Demo.Controllers
{
    public class SachOnlineController : Controller
    {
        Model1 db = new Model1();

        // GET: SachOnline
        public ActionResult Index(int? page)
        {
            var lstSaches = db.SACHes.OrderBy(s => s.Masach);
            int pageNumber = (page) ?? 1;
            int pageSize = 9;
            ViewBag.TieuDe = "SachMoi";
            return View(lstSaches.ToPagedList(pageNumber, pageSize));
            
        }

        public ActionResult ChuDePartial()
        {
            var lst = db.CHUDEs.ToList();
            return PartialView(lst);
        }


        public ActionResult NhaXuatBanPartial()
        {
            var lst = db.NHAXUATBANs.ToList();
            return PartialView(lst);
        }

        public ActionResult ChitietSach(int Masach )
        {
            var sach = db.SACHes.FirstOrDefault(s => s.Masach==Masach);

            return View(sach);
        }

        public ActionResult MenuPartial()
        {
            dynamic model = new ExpandoObject();
            model.CHUDEs = db.CHUDEs.ToList();
            model.NHAXUATBANs = db.NHAXUATBANs.ToList();
            return PartialView(model);
        }

        public ActionResult SachTheoChuDe(int MaCD, int? page)
        {

            var lstSaches = db.SACHes.Where(s => s.MaCD == MaCD).OrderBy(s => s.Masach).ToList();
            int pageNumber = (page) ?? 1;
            int pageSize = 9;
            ViewBag.TieuDe = "SÁCH THEO CHỦ ĐỀ";
            return View("Index", lstSaches.ToPagedList(pageNumber, pageSize));
        }
        public ActionResult SachTheoNXB(int MaNXB, int? page)
        {
            var lstSaches = db.SACHes.Where(s => s.MaNXB == MaNXB).OrderBy(s => s.Masach).ToList();
            int pageNumber = (page) ?? 1;
            int pageSize = 9;
            ViewBag.TieuDe = "SÁCH THEO NHÀ XUẤT BẢN";
            return View("Index", lstSaches.ToPagedList(pageNumber, pageSize));
        }
    }
}

Demo/Controllers/UserController.cs
using Demo.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Demo.Controllers
{
    public class UserController : Controller
    {
        Model1 db = new Model1();
        // GET: User
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult Dangky()
        {
           return View();
        }
        [HttpPost]
        public ActionResult DangKy(KHACHHANG Model)
        {
            if( ModelState.IsValid )
            {
                var kh = db.KHACHHANGs.FirstOrDefault(k => k.Taikhoan == Model.Taikhoan);
                if ( kh != null )
                {
                    ModelState.AddModelError("Taikhoan", "Tài khoản đã tồn tại");
                    return View();
                }
                db.KHACHHANGs.Add( Model );
                db.SaveChanges();
                return Redirect("DangNhap");
            }
            return View();
        }

        public ActionResult Dangnhap()
        { 
            return View(); 
        }
        [HttpPost]
        public ActionResult Dangnhap(UserLogin user)
        {
            if (ModelState.IsValid)
            {
                var u = db.KHACHHANGs.FirstOrDefault(k => k.Taikhoan == user.UserName && k.Matkhau == user.Password);
                if ( u == null)
                {
                    Session["Taikhoan"] = u;
                    ViewBag.ThongBao = " Đăng nhập Thành công";
                }
                else
                {
                    ModelState.AddModelError("Password","Tài khoản và mật khẩu không tồn tại");
                }
                return Redirect("~/");
            }
            return View();
        }
        public ActionResult DangXuat()
        {
            Session["Taikhoan"] = null;
            //return Redirect("Index", "SachOnline");
            return Redirect("I~/");
        }
    }
}

Demo/Views/SachOnline/ChitietSach.cshtml
@*@model Demo.Models.SACH*@
@{
    ViewBag.Title = "ChitietSach";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<h2>ChitietSach</h2>

<div class="card" ">
    <h5 class="card-title">@Model.Tensach</h5>
    <img src="@Model.Anhbia" class="card-img-top" alt="Not found image" style=" width=50px align-self:center">
    <div class="card-body">
        <p class=" card-text"> @Model.Mota</p>
        <a href="#" class="btn btn-primary">Go somewhere</a>
    </div>
</div>

Demo/Views/SachOnline/Index.cshtml
@using PagedList.Mvc;
@*@model IList<Demo.Models.SACH>*@
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}
<div class=" col-12 col-md-12">
    <h1> @ViewBag.TieuDe</h1>
    <div class="row">
        @foreach (var item in Model)
        {
            <a href=@Url.Action("ChitietSach","SachOnline", new {Masach = item.Masach})>
                <div class="card" style="width: 18rem;">
                    <img src=@item.Anhbia class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">@item.Tensach</h5>
                        <p class="card-text">@item.Mota</p>
                        <a href="#" class="btn btn-primary">Go somewhere</a>
                    </div>
                </div>
            </a>
        }
    </div>
</div>

    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

    @Html.PagedListPager(
        (PagedList.IPagedList)Model,
        page => Url.Action("Index", new { page = page })
        //PagedListRenderOptions.TwitterBootstrapPager
    )

Demo/Views/SachOnline/MenuPartial.cshtml
<head>
    <meta charset="utf-8" name="viewport" content="width=device-width, initial-scale=1">
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <script src="~/Scripts//bootstrap.min.js"></script>
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts//popper.js"></script>
    <title>@ViewBag.Title</title>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>

<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="@Url.Action("Index","SachOnline")">Home</a></li>
                <li class="nav-item"><a class="nav-link" href="@Url.Action("Dangky", "User")">đăng ký</a></li>
                <li class="nav-item"><a class="nav-link" href="@Url.Action("Dangnhap", "User")">đăng nhập</a></li>
                <li class="dropdown">
                    <a class="btn btn-secondary dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Dropdown
                    </a>
                    <div class="row">
                        <div data-bs-spy="scroll" data-bs-target="#list-example" data-bs-smooth-scroll="true" class="scrollspy-example" tabindex="0">
                            <ul class="dropdown-menu">
                                @foreach (Demo.Models.CHUDE item in Model.CHUDEs)
                                {
                                    <li><a class="dropdown-item" href="@Url.Action("SachTheoChuDe", "SachOnline", new {MaCD=item.MaCD})">@item.TenChuDe</a></li>
                                }
                            </ul>
                        </div>
                    </div>
                </li>
                <form class="d-flex" role="search">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </ul>
            <a href="@Url.Action("DangKy","User")">dang ky</a>
        </div>
    </div>
</nav>

@if (Session["Taikhoan"] != null)
{
    <a class="nav-item" href="@Url.Action("DangXuat", "User")">    Đăng Xuất    </a>

}
else
{
<a class= "nav-item" href = "@Url.Action("Dangky", "User")" > Đăng Ký </a >
<a class= "nav-item" href = "@Url.Action("DangNhap", "User") >Đăng Nhập</a>
<a class= "nav-item" href = "@Url.Action("Index", "GioHang")"> Gio Hang </a>
}

Demo/Views/SachOnline/NhaXuatBanPartial.cshtml
<div class="list-group">
    <a href="#" class="list-group-item list-group-item-action active" aria-current="true">
        Sách theo nhà xuất bản
    </a>
    @foreach (Demo.Models.NHAXUATBAN item in Model)
    {
        <a href="@Url.Action("SachTheoChuDe", "SachOnline", new {MaNXB = item.TenNXB})" class="list-group-item list-group-item-action">@item.TenNXB</a>
    }
</div>